# Generated by Django 6.0.4 on 2026-04-26 08:42

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
